WYGBlog/WYGBlog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import TemplateView
from django.contrib.sitemaps import views as sitemap_views

from blog.views import IndexView
from blog.rss import LatestPostFeed
from blog.sitemap import PostSitemap
from django.conf.urls.static import static
from django.conf import settings

from home.views import HomeListView
from WYGBlog.admin_site import admin_site
from user.views import IndexView2


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('admin-site/', admin_site.urls, name='admin-site'),

    # path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    # path('user/', include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('accounts/profile/', IndexView2.as_view(), name='user-index'),
    path('comment/', include(('comment.urls', 'comment'), namespace='comment')),
    path('rss|feed/', LatestPostFeed(), name='rss'),
    path('sitemap\.xml/', sitemap_views.sitemap, {'sitemaps': {'posts': PostSitemap}}),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('mdeditor/', include('mdeditor.urls')),

    path('', include(('home.urls', 'home'), namespace='home')),  # 博客园首页
    path('config', include(('config.urls', 'config'), namespace='config')),
    path('homeconfig/', include(('homeconfig.urls', 'homeconfig'), namespace='homeconfig')),
    # re_path(r'^(?P<blog_name>\w+)/$', IndexView.as_view(), name='blog'),  # 个人博客页
    re_path(r'^(?P<blog_name>\w+)/', include(('blog.urls', 'blog'), namespace='blog')),  # 个人博客页
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WYGBlog/blog/urls.py
from django.urls import re_path, path, include
from django.views.generic import TemplateView, RedirectView
from . import views

# from blog.apis import post_list, PostList, 
from blog.apis import PostViewSet, CategoryViewSet
from rest_framework.routers import DefaultRouter
from rest_framework.documentation import include_docs_urls

router = DefaultRouter()
# 文章的列表接口和详情接口
router.register(r'post', PostViewSet)
# 分类的列表接口和详情接口
router.register(r'category', CategoryViewSet)

urlpatterns = [
    re_path(r'^category/(?P<category_id>\d+)/$', views.CategoryView.as_view(), name='category'),
    re_path(r'^tag/(?P<tag_id>\d+)/$', views.TagView.as_view(), name='tag'),
    re_path(r'^archive/', views.ArchiveView.as_view(), name='archive'),
    re_path(r'^post/(?P<post_id>\d+).html/$', views.PostDetailView.as_view(), name='post'),
    re_path(r'^links/$', views.LinkListView.as_view(), name='links'),
    re_path(r'^search/$', views.SearchView.as_view(), name='search'),
    re_path(r'^author/(?P<owner_id>\d+)/$', views.AuthorView.as_view(), name='author'),
    re_path('about/', views.AboutView.as_view(), name='about'),
    # re_path(r'^$', views.Redirect2HomeView.as_view(), name='index'),
    path('', views.IndexView.as_view(), name='index'),
    # rest_framework
    #re_path(r'^api/post/$', post_list, name='post-list'),
    # re_path(r'^api/post/', PostList.as_view(), name='post-list'),

    # 这样定义了之后就有了两个只读的接口，
    # /api/post/
    # /api/post/<post_id>/
    # re_path(r'^api/', include((router.urls, 'router'), namespace='api')),
    # 配置接口文档  !!!!!!!!!!!!!有问题，访问/blog/api/docs/ 报错！
    # re_path(r'^api/docs/', include_docs_urls(title='WYGBlog apis')),
]

WYGBlog/user/urls.py
"""
@author:  wangyangang
@contact: wangyangang@wangyangang.com
@site:    https://wangyangang.com
@time:   2/22/20 - 4:27 PM
"""
from django.urls import re_path
from . import views

app_name = 'user'

urlpatterns = [
    re_path(r'^register/$', views.RegisterView.as_view(), name='register'),
    re_path(r'^settings/$', views.SettingsView.as_view(), name='settings'),
    re_path(r'^account-settings/$', views.AccountSettingsView.as_view(), name='account-settings'),
    # re_path(r'^login/$', views.)
    # re_path(r'^(?P<user_name>\w+)/$', views.IndexView.as_view(), name='index'),
    re_path(r'^$', views.IndexView.as_view(), name='index'),
]

WYGBlog/comment/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models import Q

import mistune

from blog.models import Post
from config.models import BlogSettings


class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除')
    )
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField(verbose_name='内容')
    content_html = models.TextField(verbose_name='html形式的内容')
    nickname = models.CharField(max_length=50, verbose_name='昵称')
    website = models.URLField(verbose_name='网站')
    email = models.EmailField(verbose_name='邮箱')
    status = models.PositiveIntegerField(default=STATUS_NORMAL,
                                         choices=STATUS_ITEMS,
                                         verbose_name='状态')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        verbose_name = verbose_name_plural = '评论'

    def __str__(self):
        # return self.content if len(self.content) <= 10 else self.content[:10]
        return self.content[:10]

    def save(self, *args, **kwargs):
        self.content_html = mistune.markdown(self.content)
        super().save(*args, **kwargs)

    @classmethod
    def get_by_blog_name(cls, blog_name):
        return cls.objects.filter(post__blog__name=blog_name, status=cls.STATUS_NORMAL)

    @classmethod
    def get_by_post(cls, post):
        return cls.objects.first(status=cls.STATUS_NORMAL, post=post)

    @classmethod
    def latest_comments(cls, blog_name):
        if not blog_name:
            return None
        else:
            ret = cls.objects.filter(post__blog__name=blog_name, status=cls.STATUS_NORMAL).order_by('-created_time')

            user_settings = BlogSettings.get_dict_by_blog_name(blog_name)  # 用户设置
            display_count = user_settings['sidebar_comment_count']  # 侧边栏评论展示的条数
            return ret[:display_count]
        # return cls.objects.filter(status=cls.STATUS_NORMAL).order_by('-created_time')

WYGBlog/blog/views.py
import os
from datetime import date

from django.shortcuts import render, HttpResponse
from django.shortcuts import get_object_or_404, Http404
from django.urls import reverse
from django.core.cache import cache
from django.views import View
from django.views.generic import DetailView, ListView, RedirectView, TemplateView
from django.db.models import Q, F
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.contrib.admin.sites import AdminSite

import markdown

from . import models
from config.models import SideBar, Link, TopBar, BlogSettings, AboutPage
from comment.models import Comment
from comment.forms import CommentForm


class CommonViewMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blog_name = self.kwargs.get('blog_name')  # 博客名

        context.update({'sidebars': SideBar.get_all_by_blog_name(blog_name)})  # 侧边栏
        context.update(models.Category.get_by_blog_name(blog_name))  # 分类导航
        context.update({'top_bars': TopBar.get_by_blog_name(blog_name)})  # 顶部菜单
        blog_setting = BlogSettings.get_dict_by_blog_name(blog_name)  # 用户设置
        context.update(dict(blog_setting))  # 用户配置
        context.update({'blog_name': blog_name})
        return context


class IndexView(CommonViewMixin, ListView):
    paginate_by = 8  # 在init方法里，读取网站配置里的首页文章展示条数
    context_object_name = 'posts'
    template_name = 'blog/index.html'

    def __init__(self):
        super().__init__()
        blog_settings = BlogSettings.objects.first()
        if blog_settings:
            IndexView.paginate_by = blog_settings.get_dict().get('index_post_count')

    def get_queryset_cache_key(self):
        """子类定制缓存key"""
        cache_key = "index_{page}".format(page=self.page_kwarg)
        return cache_key

    def get_queryset_data(self):
        """子类定制获取数据的方法"""
        blog_name = self.kwargs.get('blog_name', '')
        if blog_name:
            posts = models.Post.latest_posts(blog_name)
        else:
            posts = models.Post.latest_posts()
        return posts

    def get_queryset_from_cache(self, cache_key):
        value = cache.get(cache_key)
        if value:
            return value
        else:
            posts = self.get_queryset_data()
            cache.set(cache_key, posts)
            return posts

    def get_queryset(self, **kwargs):
        print(kwargs.get('blog_name', ''))
        # key = self.get_queryset_cache_key()
        # value = self.get_queryset_from_cache(key)
        posts = models.Post.latest_posts(self.kwargs.get('blog_name', None))
        return posts


class CategoryView(IndexView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_id = self.kwargs.get('category_id')
        category = get_object_or_404(models.Category, pk=category_id)
        context.update({'category': category})
        return context

    def get_queryset(self):
        """重写queryset，根据分类过滤"""
        queryset = super().get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id)


class TagView(IndexView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag_id = self.kwargs.get('tag_id')
        tag = get_object_or_404(models.Tag, pk=tag_id)
        context.update({"tag": tag})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        tag_id = self.kwargs.get('tag_id')
        return queryset.filter(tag__id=tag_id)


class ArchiveView(IndexView):
    template_name = 'blog/archive.html'

    def __init__(self):
        super().__init__()
        blog_settings = BlogSettings.objects.first()
        if blog_settings:
            ArchiveView.paginate_by = blog_settings.get_dict().get('archive_post_count')  # 归档页面每页展示条数


class PostDetailView(CommonViewMixin, DetailView):
    template_name = 'blog/detail.html'
    # queryset = models.Post.latest_posts()
    context_object_name = 'post'
    pk_url_kwarg = 'post_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.toc',
            'markdown.extensions.extra',
            'markdown.extensions.codehilite'
        ])
        post = context.get('post')
        post.content_html = md.convert(post.content)
        post.toc = md.toc
        context.update({'post': post})
        return context

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        self.handle_visited()
        return response

    def get_queryset(self, *args, **kwargs):
        blog_name = self.kwargs.get('blog_name')
        posts = models.Post.latest_posts(blog_name)
        return posts

    def handle_visited(self):
        increase_pv = False
        increase_uv = False
        uid = self.request.uid
        pv_key = 'pv:%s:%s' % (uid, self.request.path)
        uv_key = 'uv:%s:%s:%s' % (uid, str(date.today()), self.request.path)
        if not cache.get(pv_key):
            increase_pv = True
            cache.set(pv_key, 1, 1 * 60)

        if not cache.get(uv_key):
            increase_uv = True
            cache.set(pv_key, 1, 24 * 60 * 60)

        if increase_pv and increase_uv:
            models.Post.objects.filter(pk=self.object.id).update(pv=F('pv') + 1, uv=F('uv') + 1)
        elif increase_pv:
            models.Post.objects.filter(pk=self.object.id).update(pv=F('pv') + 1)
        elif increase_uv:
            models.Post.objects.filter(pk=self.object.id).update(uv=F('uv') + 1)


class LinkListView(CommonViewMixin, ListView):
    template_name = 'config/links.html'
    # queryset = Link.objects.filter(status=Link.STATUS_NORMAL).order_by('-weight')
    context_object_name = 'links'

    def get_queryset(self):
        links = Link.get_all_by_blog_name(self.kwargs.get('blog_name'))
        return links


class SearchView(IndexView):
    def get_queryset(self):
        queryset = super().get_queryset()
        keyword = self.request.GET.get('keyword', '')
        if not keyword:
            return queryset
        return queryset.filter(Q(title__icontains=keyword) | Q(desc__icontains=keyword))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'keyword': self.request.GET.get('keyword', '')})
        return context


class AuthorView(IndexView):
    def get_queryset(self):
        queryset = super().get_queryset()
        owner_id = self.kwargs.get('owner_id')
        return queryset.filter()


class AboutView(CommonViewMixin, TemplateView):
    template_name = 'blog/about.html'
    context_object_name = 'about'

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        self.handle_visited()
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blog_name = context.get('blog_name')
        about_objs = AboutPage.objects.filter(blog__name=blog_name)
        if not about_objs:
            return context

        md = markdown.Markdown(extensions=[
            'markdown.extensions.toc',
            'markdown.extensions.extra',
            'markdown.extensions.codehilite'
        ])
        about_objs[0].content_html = md.convert(about_objs[0].content)
        about_objs[0].toc = md.toc
        context.update({'about': about_objs[0]})
        return context

    def get_queryset(self, *args, **kwargs):
        blog_name = self.kwargs.get('blog_name')
        posts = models.Post.latest_posts(blog_name)

        return posts

    def handle_visited(self):
        increase_pv = False
        increase_uv = False
        uid = self.request.uid
        pv_key = 'pv:%s:%s' % (uid, self.request.path)
        uv_key = 'uv:%s:%s:%s' % (uid, str(date.today()), self.request.path)
        if not cache.get(pv_key):
            increase_pv = True
            cache.set(pv_key, 1, 1 * 60)

        if not cache.get(uv_key):
            increase_uv = True
            cache.set(pv_key, 1, 24 * 60 * 60)

        obj = AboutPage.objects.all()

        if increase_pv and increase_uv and obj:
            obj.update(pv=F('pv') + 1, uv=F('uv') + 1)
        elif increase_pv and obj:
            obj.update(pv=F('pv') + 1)
        elif increase_uv and obj:
            obj.update(uv=F('uv') + 1)


class Redirect2HomeView(RedirectView):
    pattern_name = 'home:index'

WYGBlog/WYGBlog/themes/bootstrap/templates/blog/archive.html
{% extends 'blog/base.html' %}

{% block title %}
    {% if category %}
        分类页：{{ category.name }}
    {% elif tag %}
        标签页：{{ tag.name }}
    {% else %}
        首页
    {% endif %}
{% endblock %}

{% block content %}
    <ul class="list-group">
        {% for post in posts %}
            <li class="list-group-item">
                <span class="badge">{{ post.created_time }}</span>
                <a href="{% url 'blog:post' blog_name post.id %}">{{ post.title }}</a>
            </li>
        {% endfor %}
    </ul>
    <!--分页-->
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
    {% endif %}
    Page {{ page_obj.number }} of {{ paginator.num_pages }}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">下一页</a>
    {% endif %}
{% endblock %}

WYGBlog/WYGBlog/themes/bootstrap/templates/blog/base.html
{% load static %}
{% load cache %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}首页{% endblock %} - WYG博客</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
    <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">

    <style>
        .fixed-header {
            position: sticky;
            position: -webkit-sticky;
            top: 0;
            z-index: 999;
        }

        .codehilite {
            padding: 0;
        }

        /* for block of numbers */
        .hljs-ln-numbers {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;

            text-align: center;
            color: #ccc;
            border-right: 1px solid #CCC;
            vertical-align: top;
            padding-right: 5px;
        }

        .hljs-ln-n {
            width: 30px;
        }

        /* for block of code */
        .hljs-ln .hljs-ln-code {
            padding-left: 10px;
            white-space: pre;
        }

        .my-toc {
            width: 260px;
        }

        .my-toc-fixed {
            width: 260px;
            position: fixed;
            top: 50px;
        }

        .my-toc > ul {
            list-style-type: none;
        }

        .my-toc-fixed > ul {
            list-style-type: none;
        }
    </style>
    {% block extra_head %}

    {% endblock %}
</head>
<body>
<div class="container head fixed-header">
    <nav class="navbar navbar-expand-lg navbar-default bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div style="float: left">
                <ul class="nav navbar-nav">
                    <li class="nav-item"><a href="{% url 'blog:index' blog_name %}" class="nav-link">首页</a></li>
                </ul>
            </div>

            <div style="float: right">
                <div style="float: left">
                    <ul class="nav navbar-nav">
                        {% for top_bar in top_bars %}
                            <li class="nav-item">
                                {% if top_bar.display_type == 1 %}
                                    <a class="nav-link" href="{{ top_bar.link }}" target="_blank">{{ top_bar.name }}</a>
                                {% else %}
                                    <a class="nav-link" href="{{ top_bar.link }}">{{ top_bar.name }}</a>
                                {% endif %}
                            </li>
                        {% endfor %}
{#                        <li class="nav-item"><a href="#" class="nav-link">|</a></li>#}
                        {% for nav_category in nav_categories %}
                            <li class="nav-item">
                                <a class="nav-link"
                                   href="{% url 'blog:category' blog_name nav_category.id %}">{{ nav_category.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div style="float: left;">
                    <form action="{% url 'blog:search' blog_name %}" class="navbar-form navbar-right" method="get">
                        <input type="search" class="form-control mr-sm-2"
                               placeholder="Search" aria-label="Search" name="keyword" value="{{ keyword }}">
                        <button class="btn btn-outline-success" type="submit">搜索</button>
                    </form>
                </div>
                <div class="dropdown" style="float: right;margin: 8px 0 0 10px">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        <a href="#">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                            {% if user.is_authenticated %}
                                <span class="glyphicon-class">{{ user.username }}</span>
                            {% endif %}
                        </a>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'user:index' %}">我的主页</a></li>
                            <li><a href="{% url 'logout' %}?next={{ request.path }}">注销</a></li>
                            <li role="separator" class="divider"></li>
                        {% else %}
                            <li><a href="{% url 'user:register' %}?next={{ request.path }}">注册</a></li>
                            <li><a href="{% url 'login' %}?next={{ request.path }}">登录</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </nav>
</div>

<div class="container main main2">
    <div class="row">
        <div class="col-lg-3">
            {% block sidebar %}
                {% for sidebar in sidebars %}
                    <div class="panel panel-default">
                        <div class="panel-heading">{{ sidebar.title }}</div>
                        <ul class="list-group">
                            {% if sidebar.display_type == 1 %}  {# 显示html不需要转义 #}
                                {{ sidebar.content_html|safe }}
                            {% else %}
                                {{ sidebar.content_html }}
                            {% endif %}
                        </ul>
                    </div>
                {% endfor %}
            {% endblock %}

            <div id="my-toc" class="my-toc">
                {% block toc %}
                {% endblock toc %}
            </div>
        </div>

        <div class="col-lg-9">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</div>

<footer class="footer">
    {% block footer %}
        <div class="container">
            <hr>
            <nav class="nav category">
                {% for normal_category in normal_categories %}
                    <a href="{% url 'blog:category' blog_name normal_category.id %}"
                       class="nav-link">{{ normal_category.name }}</a>
                {% endfor %}
            </nav>
        </div>
        <div class="container power" style="text-align: center;">
            <span class="text-muted">Power by <a href="https://github.com/wangyangang/">WYGBlog</a>@wangyangang</span>
            <span class="text-muted">京ICP备19041399号</span>
        </div>
    {% endblock %}
</footer>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/dropdown.js' %}"></script>
<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
{#<script src="{% static 'js/highlight.js' %}"></script>#}
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
{#<script src="{% static 'js/highlightjs-line-numbers.js' %}"></script>#}
<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>

{% block jsblock %}

{% endblock %}
</body>
</html>

WYGBlog/WYGBlog/themes/bootstrap/templates/blog/detail.html
{% extends "blog/base.html" %}
{% load static %}
{% load comment_block %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/highlight_googlecode.css' %}">
    <script src="{% static 'js/highlight.js' %}"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <style>
        .esa-post-signature {
            padding: 12px 24px 12px 30px;
            margin-top: 15px;
            margin-left: 5px;
            border-left-width: 4px;
            font-size: 15px;
            line-height: 2;
            border-left-style: solid;
            background-color: #f8f8f8;
            position: relative;
            border-bottom-right-radius: 2px;
            border-top-right-radius: 2px;
            border-left-color: #2D8CF0;
            z-index: 1;
        }

        .esa-post-signature:before {
            content: "!";
            background-color: #2D8CF0;
            position: absolute;
            top: 25px;
            left: -12px;
            color: #fff;
            width: 20px;
            height: 20px;
            border-radius: 100%;
            text-align: center;
            line-height: 20px;
            font-weight: 700;
            font-size: 14px;
        }

        .esa-post-signature p {
            margin: 0 !important;
        }

        #blog_post_info_block {
            margin-top: 20px;
        }

        #BlogPostCategory {
            font-size: 14px;
            margin-bottom: 0;
        }

        .postDesc {
            float: right;
            width: 100%;
            text-align: right;
            font-size: 13px;
            font-weight: 300;
            padding-right: 0 !important;
            color: #314659 !important;
            clear: both;
            margin-top: 1px;
            border-top: 1px solid slategray;
            margin-bottom: 10px;
        }
    </style>
{% endblock %}

{% block content %}

    {% if post %}

        {{ post.content_html|safe }}
        <!--标签-->
        <div>标签：
            {% for t in post.tag.all %}
                <span> <a href="{% url 'blog:tag' blog_name t.id %}">{{ t.name }}</a></span>
            {% endfor %}
        </div>

        <div id="MySignature">
            <div class="esa-post-signature">
                <p>作者:&nbsp;<a href="{% url 'blog:index' post.blog.name %}">{{ post.blog.user.username }}</a></p>
                <p>出处:&nbsp;<a
                        href="{% url 'blog:post' blog_name post.id %}">{% url 'blog:post' blog_name post.id %}</a></p>
                <p>版权:&nbsp;本文采用
                    <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">
                        署名-非商业性使用-相同方式共享 4.0 国际
                    </a>
                    知识共享许可协议进行许可。
                </p>
            </div>
        </div>

        <div id="blog_post_info_block">
            <div id="BlogPostCategory">
                分类: <a href="{% url 'blog:category' blog_name post.category.id %}">{{ post.category.name }}</a>
                {% for tag in post.tag.all %}
                    标签: <a href="{% url 'blog:tag' blog_name tag.id %}">{{ tag.name }}</a>
                {% endfor %}
            </div>
        </div>

        <div class="postDesc">
            posted @ <span id="post-date">{{ post.created_time }}</span>&nbsp;
            <a href="{% url 'blog:index' post.blog.name %}">{{ post.blog.user.username }}</a>&nbsp;
            阅读(<span id="post_view_count">{{ post.pv }}</span>)&nbsp;
            评论(<span id="post_comment_count">{{ post.comment_set.count }}</span>)&nbsp;
            <a href="{% url 'admin:blog_post_change' post.id %}">编辑</a>
        </div>

        {% comment_block post blog_name %}
    {% endif %}

{% endblock %}

{% block toc %}
    <div id="my-toc">
        {{ post.toc|safe }}
    </div>
{% endblock %}

{% block jsblock %}
    <script type="text/javascript">
        window.onload =
            function () {
                var oDiv = document.getElementById("my-toc"),
                    H = -50,
                    Y = oDiv
                while (Y) {
                    H += Y.offsetTop;
                    Y = Y.offsetParent
                }
                window.onscroll = function () {
                    var s = document.body.scrollTop || document.documentElement.scrollTop
                    if (s > H) {
                        {#oDiv.style = "position:fixed; top:50px; width:260px;"#}
                        oDiv.className = 'my-toc-fixed'
                    } else {
                        {#oDiv.style = "width:260px;"#}
                        oDiv.className = 'my-toc'
                    }
                }
            }
    </script>
{% endblock %}

WYGBlog/WYGBlog/themes/bootstrap/templates/blog/index.html
{% extends "blog/base.html" %}

{% block title %}
    {% if category %}
        分类页：{{ category.name }}
    {% elif tag %}
        标签页：{{ tag.name }}
    {% else %}
        首页
    {% endif %}
{% endblock %}

{% block extra_head %}
    <style>
        .align-right {
            text-align: right;
        }

        .no-padding-bottom {
            padding-bottom: 10px;
            padding-top: 5px;
        }
    </style>
{% endblock %}

{% block content %}
    {% for post in posts %}
        <h5 class="card-title">
            <a href="{% url 'blog:post' blog_name post.id %}">{{ post.title }}</a>
        </h5>

        <p class="card-text">{{ post.desc }}<a href="{% url 'blog:post' blog_name post.id %}">......阅读全文</a></p>

        <div class="tag-font align-right">
            <span class="card-link">作者: <a
                    href="{% url 'user:index' %}">{{ post.blog.user.username }}</a></span>&nbsp;
            <span class="card-link">分类:<a
                    href="{% url 'blog:category' blog_name post.category.id %}">{{ post.category.name }}</a></span>
            <span class="card-link">标签:
                {% for tag in post.tag.all %}
                    <a href="{% url 'blog:tag' blog_name tag.id %}">{{ tag.name }}</a>
                {% endfor %}
            </span>
        </div>
        <hr>
    {% endfor %}

    <!--分页-->
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
    {% endif %}

    {% if paginator.count %}
        Page {{ page_obj.number }} of {{ paginator.num_pages }}
    {% endif %}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">下一页</a>
    {% endif %}
{% endblock %}