WYGBlog/WYGBlog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import TemplateView
from django.contrib.sitemaps import views as sitemap_views

from blog.views import IndexView
from blog.rss import LatestPostFeed
from blog.sitemap import PostSitemap
from django.conf.urls.static import static
from django.conf import settings

from home.views import HomeListView
from WYGBlog.admin_site import admin_site
from user.views import IndexView2


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('admin-site/', admin_site.urls, name='admin-site'),

    # path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    # path('user/', include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('accounts/profile/', IndexView2.as_view(), name='user-index'),
    path('comment/', include(('comment.urls', 'comment'), namespace='comment')),
    path('rss|feed/', LatestPostFeed(), name='rss'),
    path('sitemap\.xml/', sitemap_views.sitemap, {'sitemaps': {'posts': PostSitemap}}),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('mdeditor/', include('mdeditor.urls')),

    path('', include(('home.urls', 'home'), namespace='home')),  # 博客园首页
    path('config', include(('config.urls', 'config'), namespace='config')),
    path('homeconfig/', include(('homeconfig.urls', 'homeconfig'), namespace='homeconfig')),
    # re_path(r'^(?P<blog_name>\w+)/$', IndexView.as_view(), name='blog'),  # 个人博客页
    re_path(r'^(?P<blog_name>\w+)/', include(('blog.urls', 'blog'), namespace='blog')),  # 个人博客页
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WYGBlog/blog/urls.py
from django.urls import re_path, path, include
from django.views.generic import TemplateView, RedirectView
from . import views

# from blog.apis import post_list, PostList, 
from blog.apis import PostViewSet, CategoryViewSet
from rest_framework.routers import DefaultRouter
from rest_framework.documentation import include_docs_urls

router = DefaultRouter()
# 文章的列表接口和详情接口
router.register(r'post', PostViewSet)
# 分类的列表接口和详情接口
router.register(r'category', CategoryViewSet)

urlpatterns = [
    re_path(r'^category/(?P<category_id>\d+)/$', views.CategoryView.as_view(), name='category'),
    re_path(r'^tag/(?P<tag_id>\d+)/$', views.TagView.as_view(), name='tag'),
    re_path(r'^archive/', views.ArchiveView.as_view(), name='archive'),
    re_path(r'^post/(?P<post_id>\d+).html/$', views.PostDetailView.as_view(), name='post'),
    re_path(r'^links/$', views.LinkListView.as_view(), name='links'),
    re_path(r'^search/$', views.SearchView.as_view(), name='search'),
    re_path(r'^author/(?P<owner_id>\d+)/$', views.AuthorView.as_view(), name='author'),
    re_path('about/', views.AboutView.as_view(), name='about'),
    # re_path(r'^$', views.Redirect2HomeView.as_view(), name='index'),
    path('', views.IndexView.as_view(), name='index'),
    # rest_framework
    #re_path(r'^api/post/$', post_list, name='post-list'),
    # re_path(r'^api/post/', PostList.as_view(), name='post-list'),

    # 这样定义了之后就有了两个只读的接口，
    # /api/post/
    # /api/post/<post_id>/
    # re_path(r'^api/', include((router.urls, 'router'), namespace='api')),
    # 配置接口文档  !!!!!!!!!!!!!有问题，访问/blog/api/docs/ 报错！
    # re_path(r'^api/docs/', include_docs_urls(title='WYGBlog apis')),
]

WYGBlog/user/urls.py
"""
@author:  wangyangang
@contact: wangyangang@wangyangang.com
@site:    https://wangyangang.com
@time:   2/22/20 - 4:27 PM
"""
from django.urls import re_path
from . import views

app_name = 'user'

urlpatterns = [
    re_path(r'^register/$', views.RegisterView.as_view(), name='register'),
    re_path(r'^settings/$', views.SettingsView.as_view(), name='settings'),
    re_path(r'^account-settings/$', views.AccountSettingsView.as_view(), name='account-settings'),
    # re_path(r'^login/$', views.)
    # re_path(r'^(?P<user_name>\w+)/$', views.IndexView.as_view(), name='index'),
    re_path(r'^$', views.IndexView.as_view(), name='index'),
]

WYGBlog/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.contrib.sites.models import Site


class BlogUser(AbstractUser):
    nickname = models.CharField('昵称', max_length=100, null=True, blank=True)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    modified_time = models.DateTimeField('修改时间', auto_now_add=True)

    def get_absolute_url(self):
        return reverse('user:index')

    def __str__(self):
        return self.username

    def get_full_url(self):
        site = Site.objects.get_current()
        url = 'https://{site}{path}'.format(site.domain, self.get_absolute_url())
        return url

    class Meta:
        ordering = ['-id']
        verbose_name = verbose_name_plural = '用户'
        get_latest_by = 'id'

WYGBlog/user/forms.py
"""
@author:  wangyangang
@contact: wangyangang@wangyangang.com
@site:    https://wangyangang.com
@time:   2/25/20 - 1:41 AM
"""
from django.contrib.auth.forms import UserCreationForm

from user.models import BlogUser


class RegisterForm(UserCreationForm):
    class Meta:
        model = BlogUser
        fields = ('username', 'email')

WYGBlog/user/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views import View
from django.contrib.auth.models import User
from django.shortcuts import redirect, reverse
from django.conf import settings
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.shortcuts import HttpResponse

from user.models import BlogUser
from user.forms import RegisterForm


class CommenViewMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_name = self.request.user.username
        context.update({'user_name': user_name})
        return context


class IndexView(CommenViewMixin, LoginRequiredMixin, ListView):
    template_name = 'user/index.html'

    def get_queryset(self):
        return self.request.user.username


class IndexView2(View):
    def get(self, request):
        return render(request, 'accounts/profile.html')


class RegisterView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('user:index')
        form = RegisterForm()
        next_url = request.GET.get('next', '/')
        return render(request, 'user/register.html', {'form': form, 'next': next_url})

    def post(self, request):
        next_url = request.POST.get('next', '/')
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(next_url)
        else:
            return render(request, 'user/register.html', {'form': form, 'next': next_url})


class SettingsView(View):
    def get(self, request):
        return render(request, 'user/settings.html')

    def post(self, request):
        pass


class AccountSettingsView(View):
    def post(self, request):
        return HttpResponse(request.POST.get('username'))

WYGBlog/WYGBlog/themes/bootstrap/templates/user/account_settings.html
<form class="form-horizontal" style="padding: 10px 80px 0 0;"
      method="post" action="{% url 'user:account-settings' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="inputUsername3" class="col-sm-2 control-label">登录用户名</label>
        <div class="col-sm-10">
            <input name="username" type="text" class="form-control" id="inputUsername3"
                   placeholder="登录用户名">
        </div>
    </div>

    <div id="div1" class="form-group">
        <label for="input1" class="col-sm-2 control-label">新用户名</label>
        <div class="col-sm-10">
            <input class="form-control form" type="text" value="cancel" onclick="$('#div1').show();">
            <button class="form-control form-inline" onclick="$('#div1').hide();">abc</button>
        </div>
    </div>

    <div class="form-group">
        <label for="inputPassword3" class="col-sm-2 control-label">密码</label>
        <div class="col-sm-10">
            <input type="password" class="form-control" id="inputPassword3" placeholder="密码">
        </div>
    </div>
    <div class="form-group">
        <label for="inputNickname3" class="col-sm-2 control-label">显示昵称</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="inputNickname3" placeholder="显示昵称">
        </div>
    </div>
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">邮箱</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" id="inputEmail3" placeholder="邮箱">
        </div>
    </div>
    <div class="form-group">
        <label for="inputPhone" class="col-sm-2 control-label">手机</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="inputPhone" placeholder="手机">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">保存</button>
        </div>
    </div>

</form>

WYGBlog/WYGBlog/themes/bootstrap/templates/user/index.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        ul {
            padding: 0;
        }

        li {
            list-style: none;
        }

        a {
            text-decoration: #34ce57;
        }

        .text_gray {
            color: gray;
        }

        .data_left {
            float: left;
            border-right: 1px solid #bbb;
            padding-right: 15px;
            margin-right: 15px;
        }

        .data_right {
            float: left;
        }

        .topic_nav_block_wrapper {
            background-color: White;
            border-bottom: 1px solid #C8D3DE;
        }

        .mini_nav_block {
            font-size: 12px;
            float: right;
            margin-bottom: -1px;
            padding-right: 10px;
            width: 380px;
        }

        .mini_nav_block li {
            float: right;
            margin-right: 3px;
        }

        .mini_nav_block a:link, .mini_nav_block a:visited, .mini_nav_block a:active {
            background-color: #59a0e1;
            border: 1px solid #59a0e1;
            color: #fff;
            float: left;
            letter-spacing: 1px;
            padding: 2px 6px 1px;
            text-decoration: none;
        }

        .title_block {
            border: none;
            width: 80px;
            float: left;
            font-size: 14px;
            font-weight: bold;
            padding-left: 10px;
            color: #454545;
        }

        .clear {
            clear: both;
        }

        .link_modify_info {
            background: url({% static 'images/ico_modify_info.gif' %}) no-repeat left center;
            padding-left: 20px;
        }

        .link_account {
            background: url({% static 'images/ico_account.gif' %}) no-repeat left center;
            padding-left: 20px;
        }

        .link_mying {
            background: url({% static 'images/ico_ing.gif' %}) no-repeat left center;
            padding-left: 20px;
        }

        .link_question {
            background: url({% static 'images/ico_question.gif' %}) no-repeat left center;
            padding-left: 20px;
        }
    </style>
    {% block top-files %}

    {% endblock %}
</head>
<body>
<div class="container">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="#">博客园</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'blog:index' user.blog.name %}">我的博客</a></li>
                    <li><a href="{% url 'user:index' %}">我的园子</a></li>
                    <li><a href="{% url 'user:settings' %}">设置</a></li>
                    <li><a href="{% url 'logout' %}">退出</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</div>

{% block main %}

<div class="container main">
    <div class="row">
        <div class="col-md-2">
            <ul class="list-group">
                <li class="list-group-item">收藏</li>
                <li class="list-group-item">博客</li>
                <li class="list-group-item">个人信息</li>
                <li class="list-group-item">Porta ac consectetur ac</li>
                <li class="list-group-item">Vestibulum at eros</li>
            </ul>
        </div>
        <div class="col-md-7">
            <div class="media" style="padding-top: 20px;">
                <div class="media-left">
                    <a href="#">
                        <img class="media-object" src="{% static 'images/bigbai.png' %}" alt="...">
                    </a>
                    <table class="user_profile_nav_block">
                        <tbody>
                        <tr>
                            <td>
                                <ul class="avatar_nav_block" id="avatar_opt_nav">
                                    <li><a href="#" class="link_modify_info">修改头像</a></li>
                                    <li><a href="#" class="link_account">个人资料</a></li>
                                    <li><a href="#" class="link_mying">闪存主页</a></li>
                                    <li><a href="#" class="link_question">博问主页</a></li>
                                </ul>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">王延刚</h4>
                    <a href="{% url 'password_change' %}?next={{ request.path }}">修改密码</a>
                    <ul>
                        <li><span>姓名:</span><span>王延刚</span></li>
                        <li><span>性别:</span><span>男</span></li>
                        <li><span>家乡:</span><span>山东枣庄</span></li>
                        <li><span>现居住地:</span><span>北京昌平</span></li>
                        <li><span>园龄:</span><span>3年2个月</span></li>
                        <li><span>博客:</span><a href="#">https://example.com</a></li>
                    </ul>
                    <div class="text_gray" style="padding-top: 10px;">
                        <div class="data_count_block" style="padding: 0px 0 15px;">
                            <div class="data_left">
                                <div class="follow_count"><a id="following_count"
                                                             href="#">6</a>
                                </div>
                                <a href="#">关注</a>
                            </div>
                            <div class="data_right">
                                <div class="follow_count"><a id="follower_count"
                                                             href="#">0</a>
                                </div>
                                <a href="#">粉丝</a>
                            </div>
                            <div class="clear">
                            </div>
                        </div>
                    </div>
                </div>


            </div>

            <div class="topic_nav_block_wrapper">
                <ul class="mini_nav_block">
                    <li><a href="javascript:void(0)" data-apptype="question">博问</a></li>
                    <li><a href="javascript:void(0)" data-apptype="blog">博客</a></li>
                    <li><a href="javascript:void(0)" data-apptype="all" class="current_nav">全部</a></li>
                </ul>
                <span class="title_block">最新动态</span>
                <div class="clear">
                </div>
            </div>

        </div>
        <div class="col-md-3">
            >
        </div>
    </div>
</div>

{% endblock main %}

{% block js-block %}

{% endblock %}
</body>
</html>

WYGBlog/WYGBlog/themes/bootstrap/templates/user/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <style>
        .register {
            width: 290px;
            height: 500px;
            border: 1px solid #EEEEEE;
            margin: 20px auto;
            padding: 5px;
        }

    </style>
</head>
<body>
<div class="container">
    <div class="register">
        <h3>注册</h3>
        <form class="form-horizontal" action="{% url 'user:register' %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                {{ field.label_tag }}
                {{ field }}
                <span style="color: red;">{{ field.errors }}</span>
                {% if field.help_text %}
                    <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                {% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-primary btn-block">注册</button>
            <input type="hidden" name="next" value="{{ next }}">
        </form>
        <div class="flex-center top-gap text-small">
            <a href="{% url 'login' %}?next={{ request.path }}">已有账号登录</a>
        </div>
    </div>
</div>
</body>
</html>

WYGBlog/WYGBlog/themes/bootstrap/templates/user/settings.html
{% extends 'user/index.html' %}
{% load static %}
{% block top-files %}

{% endblock %}

{% block main %}
    <div class="container">

        <ul id="myTab" class="nav nav-tabs">
            <li class="active"><a href="#home" data-toggle="tab">账户设置</a></li>
            <li><a href="#ios" data-toggle="tab">个人资料</a></li>
            <li><a href="#ios" data-toggle="tab">头像设置</a></li>
            <li><a href="{% url 'admin:index' %}" data-toggle="">博客设置</a></li>
        </ul>
        <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade in active" id="home">
                {% include 'user/account_settings.html' %}
            </div>
            <div class="tab-pane fade" id="ios">
                <p>iOS 是一个由苹果公司开发和发布的手机操作系统。最初是于 2007 年首次发布 iPhone、iPod Touch 和 Apple
                    TV。iOS 派生自 OS X，它们共享 Darwin 基础。OS X 操作系统是用在苹果电脑上，iOS 是苹果的移动版本。</p>
            </div>
            <div class="tab-pane fade" id="jmeter">
                <p>jMeter 是一款开源的测试软件。它是 100% 纯 Java 应用程序，用于负载和性能测试。</p>
            </div>
            <div class="tab-pane fade" id="ejb">
                <p>Enterprise Java Beans（EJB）是一个创建高度可扩展性和强大企业级应用程序的开发架构，部署在兼容应用程序服务器（比如 JBOSS、Web Logic 等）的 J2EE 上。
                </p>
            </div>
        </div>
    </div>
{% endblock %}