WYGBlog/WYGBlog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import TemplateView
from django.contrib.sitemaps import views as sitemap_views

from blog.views import IndexView
from blog.rss import LatestPostFeed
from blog.sitemap import PostSitemap
from django.conf.urls.static import static
from django.conf import settings

from home.views import HomeListView
from WYGBlog.admin_site import admin_site
from user.views import IndexView2


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('admin-site/', admin_site.urls, name='admin-site'),

    # path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    # path('user/', include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('accounts/profile/', IndexView2.as_view(), name='user-index'),
    path('comment/', include(('comment.urls', 'comment'), namespace='comment')),
    path('rss|feed/', LatestPostFeed(), name='rss'),
    path('sitemap\.xml/', sitemap_views.sitemap, {'sitemaps': {'posts': PostSitemap}}),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('mdeditor/', include('mdeditor.urls')),

    path('', include(('home.urls', 'home'), namespace='home')),  # 博客园首页
    path('config', include(('config.urls', 'config'), namespace='config')),
    path('homeconfig/', include(('homeconfig.urls', 'homeconfig'), namespace='homeconfig')),
    # re_path(r'^(?P<blog_name>\w+)/$', IndexView.as_view(), name='blog'),  # 个人博客页
    re_path(r'^(?P<blog_name>\w+)/', include(('blog.urls', 'blog'), namespace='blog')),  # 个人博客页
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WYGBlog/blog/urls.py
from django.urls import re_path, path, include
from django.views.generic import TemplateView, RedirectView
from . import views

# from blog.apis import post_list, PostList, 
from blog.apis import PostViewSet, CategoryViewSet
from rest_framework.routers import DefaultRouter
from rest_framework.documentation import include_docs_urls

router = DefaultRouter()
# 文章的列表接口和详情接口
router.register(r'post', PostViewSet)
# 分类的列表接口和详情接口
router.register(r'category', CategoryViewSet)

urlpatterns = [
    re_path(r'^category/(?P<category_id>\d+)/$', views.CategoryView.as_view(), name='category'),
    re_path(r'^tag/(?P<tag_id>\d+)/$', views.TagView.as_view(), name='tag'),
    re_path(r'^archive/', views.ArchiveView.as_view(), name='archive'),
    re_path(r'^post/(?P<post_id>\d+).html/$', views.PostDetailView.as_view(), name='post'),
    re_path(r'^links/$', views.LinkListView.as_view(), name='links'),
    re_path(r'^search/$', views.SearchView.as_view(), name='search'),
    re_path(r'^author/(?P<owner_id>\d+)/$', views.AuthorView.as_view(), name='author'),
    re_path('about/', views.AboutView.as_view(), name='about'),
    # re_path(r'^$', views.Redirect2HomeView.as_view(), name='index'),
    path('', views.IndexView.as_view(), name='index'),
    # rest_framework
    #re_path(r'^api/post/$', post_list, name='post-list'),
    # re_path(r'^api/post/', PostList.as_view(), name='post-list'),

    # 这样定义了之后就有了两个只读的接口，
    # /api/post/
    # /api/post/<post_id>/
    # re_path(r'^api/', include((router.urls, 'router'), namespace='api')),
    # 配置接口文档  !!!!!!!!!!!!!有问题，访问/blog/api/docs/ 报错！
    # re_path(r'^api/docs/', include_docs_urls(title='WYGBlog apis')),
]

WYGBlog/comment/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^add_comment', views.AddCommentView.as_view(), name='add_comment')
]

WYGBlog/comment/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models import Q

import mistune

from blog.models import Post
from config.models import BlogSettings


class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除')
    )
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField(verbose_name='内容')
    content_html = models.TextField(verbose_name='html形式的内容')
    nickname = models.CharField(max_length=50, verbose_name='昵称')
    website = models.URLField(verbose_name='网站')
    email = models.EmailField(verbose_name='邮箱')
    status = models.PositiveIntegerField(default=STATUS_NORMAL,
                                         choices=STATUS_ITEMS,
                                         verbose_name='状态')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        verbose_name = verbose_name_plural = '评论'

    def __str__(self):
        # return self.content if len(self.content) <= 10 else self.content[:10]
        return self.content[:10]

    def save(self, *args, **kwargs):
        self.content_html = mistune.markdown(self.content)
        super().save(*args, **kwargs)

    @classmethod
    def get_by_blog_name(cls, blog_name):
        return cls.objects.filter(post__blog__name=blog_name, status=cls.STATUS_NORMAL)

    @classmethod
    def get_by_post(cls, post):
        return cls.objects.first(status=cls.STATUS_NORMAL, post=post)

    @classmethod
    def latest_comments(cls, blog_name):
        if not blog_name:
            return None
        else:
            ret = cls.objects.filter(post__blog__name=blog_name, status=cls.STATUS_NORMAL).order_by('-created_time')

            user_settings = BlogSettings.get_dict_by_blog_name(blog_name)  # 用户设置
            display_count = user_settings['sidebar_comment_count']  # 侧边栏评论展示的条数
            return ret[:display_count]
        # return cls.objects.filter(status=cls.STATUS_NORMAL).order_by('-created_time')

WYGBlog/comment/forms.py
from django import forms

import mistune

from .models import Comment


class CommentForm(forms.ModelForm):
    nickname = forms.CharField(label='昵称',
                               max_length=50,
                               widget=forms.widgets.Input(
                                   attrs={'class': 'form-control', 'style': 'width:60%;'}
                               ))
    email = forms.CharField(label='Email',
                            max_length=50,
                            widget=forms.widgets.EmailInput(
                                attrs={'class': 'form-control', 'style': 'width:60%;'}
                            ))
    website = forms.CharField(label='网站',
                              max_length=100,
                              widget=forms.widgets.URLInput(
                                  attrs={'class': 'form-control', 'style': 'width:60%;'}
                              ))
    content = forms.CharField(label='内容',
                              max_length=500,
                              widget=forms.widgets.Textarea(
                                  attrs={'rows': 6, 'cols': 60, 'class': 'form-control'}
                              ),
                              help_text='请输入不少于10个字符')

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if len(content) < 10:
            raise forms.ValidationError('内容太短')

        # content = mistune.markdown(content)  # 把markdown格式，转为HTML，并保存起来
        return content

    class Meta:
        model = Comment
        fields = ['nickname', 'email', 'website', 'content']

WYGBlog/comment/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import TemplateView

from .forms import CommentForm


class AddCommentView(TemplateView):
    http_method_names = ['post']
    template_name = 'comment/result.html'

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        post_id = request.POST.get('post')
        blog_name = request.POST.get('blog_name')

        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.post_id = post_id
            instance.save()
            succeed = True
            return redirect(reverse('blog:post', args=(blog_name, post_id)))
        else:
            succeed = False

        context = {
            'succeed': succeed,
            'form': comment_form,
            'post': post_id
        }
        return self.render_to_response(context)

WYGBlog/WYGBlog/themes/bootstrap/templates/comment/block.html
    <div class="comment">
        <form action="{% url 'comment:add_comment' %}" method="post" class="form-group">
            {% csrf_token%}
            <input type="hidden" name="post" value="{{ post.id }}">
            <input type="hidden" name="blog_name" value="{{ blog_name }}">
            <span style="font-size: 20px;">发表评论</span> <br>
            {{ comment_form }}
            <input type="submit" value="提交评论" class="btn-block btn-primary btn-group-lg">
        </form>

        <!--评论列表-->
        <ul class="list-group">
            {% for comment in comments %}
                <li class="list-group-item">
                    <div class="nickname">
                        <a href="{{ comment.website }}">{{ comment.nickname }}</a>
                        <span>{{ comment.created_time }}</span>
                    </div>
                    <div class="comment-content">
                        {{ comment.content_html|safe }}
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>

WYGBlog/WYGBlog/themes/bootstrap/templates/comment/result.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>评论结果页</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
    <style>
        body{
            text-align: center;
        }
        .result{
            text-align: center;
            width: 40%;
            margin: auto;
        }
        .errorlist{
            color:red;
        }
        ul li{
            list-style-type: none;
        }
    </style>
</head>
<body>
    <div class="result">
        {% if succeed %}
            评论成功!
            <a href="{% url 'blog:post' post_id %}">返回</a>
        {% else %}
            <ul class="errorlist">
                {% for field, message in form.errors.items %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
            <a href="javascript:window.history.back();">返回</a>
        {% endif %}
    </div>
</body>
</html>