WYGBlog/WYGBlog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import TemplateView
from django.contrib.sitemaps import views as sitemap_views

from blog.views import IndexView
from blog.rss import LatestPostFeed
from blog.sitemap import PostSitemap
from django.conf.urls.static import static
from django.conf import settings

from home.views import HomeListView
from WYGBlog.admin_site import admin_site
from user.views import IndexView2


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('admin-site/', admin_site.urls, name='admin-site'),

    # path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    # path('user/', include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('accounts/profile/', IndexView2.as_view(), name='user-index'),
    path('comment/', include(('comment.urls', 'comment'), namespace='comment')),
    path('rss|feed/', LatestPostFeed(), name='rss'),
    path('sitemap\.xml/', sitemap_views.sitemap, {'sitemaps': {'posts': PostSitemap}}),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('mdeditor/', include('mdeditor.urls')),

    path('', include(('home.urls', 'home'), namespace='home')),  # 博客园首页
    path('config', include(('config.urls', 'config'), namespace='config')),
    path('homeconfig/', include(('homeconfig.urls', 'homeconfig'), namespace='homeconfig')),
    # re_path(r'^(?P<blog_name>\w+)/$', IndexView.as_view(), name='blog'),  # 个人博客页
    re_path(r'^(?P<blog_name>\w+)/', include(('blog.urls', 'blog'), namespace='blog')),  # 个人博客页
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WYGBlog/blog/urls.py
from django.urls import re_path, path, include
from django.views.generic import TemplateView, RedirectView
from . import views

# from blog.apis import post_list, PostList, 
from blog.apis import PostViewSet, CategoryViewSet
from rest_framework.routers import DefaultRouter
from rest_framework.documentation import include_docs_urls

router = DefaultRouter()
# 文章的列表接口和详情接口
router.register(r'post', PostViewSet)
# 分类的列表接口和详情接口
router.register(r'category', CategoryViewSet)

urlpatterns = [
    re_path(r'^category/(?P<category_id>\d+)/$', views.CategoryView.as_view(), name='category'),
    re_path(r'^tag/(?P<tag_id>\d+)/$', views.TagView.as_view(), name='tag'),
    re_path(r'^archive/', views.ArchiveView.as_view(), name='archive'),
    re_path(r'^post/(?P<post_id>\d+).html/$', views.PostDetailView.as_view(), name='post'),
    re_path(r'^links/$', views.LinkListView.as_view(), name='links'),
    re_path(r'^search/$', views.SearchView.as_view(), name='search'),
    re_path(r'^author/(?P<owner_id>\d+)/$', views.AuthorView.as_view(), name='author'),
    re_path('about/', views.AboutView.as_view(), name='about'),
    # re_path(r'^$', views.Redirect2HomeView.as_view(), name='index'),
    path('', views.IndexView.as_view(), name='index'),
    # rest_framework
    #re_path(r'^api/post/$', post_list, name='post-list'),
    # re_path(r'^api/post/', PostList.as_view(), name='post-list'),

    # 这样定义了之后就有了两个只读的接口，
    # /api/post/
    # /api/post/<post_id>/
    # re_path(r'^api/', include((router.urls, 'router'), namespace='api')),
    # 配置接口文档  !!!!!!!!!!!!!有问题，访问/blog/api/docs/ 报错！
    # re_path(r'^api/docs/', include_docs_urls(title='WYGBlog apis')),
]

WYGBlog/home/urls.py
"""
@author:  wangyangang
@contact: wangyangang@wangyangang.com
@site:    https://wangyangang.com
@time:   2/21/20 - 2:05 PM
"""

from django.urls import path

from . import views

from . import views
urlpatterns = [
    path('', views.HomeListView.as_view(), name='index'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('category/<category_id>/', views.CategoryView.as_view(), name='category'),
]

WYGBlog/user/urls.py
"""
@author:  wangyangang
@contact: wangyangang@wangyangang.com
@site:    https://wangyangang.com
@time:   2/22/20 - 4:27 PM
"""
from django.urls import re_path
from . import views

app_name = 'user'

urlpatterns = [
    re_path(r'^register/$', views.RegisterView.as_view(), name='register'),
    re_path(r'^settings/$', views.SettingsView.as_view(), name='settings'),
    re_path(r'^account-settings/$', views.AccountSettingsView.as_view(), name='account-settings'),
    # re_path(r'^login/$', views.)
    # re_path(r'^(?P<user_name>\w+)/$', views.IndexView.as_view(), name='index'),
    re_path(r'^$', views.IndexView.as_view(), name='index'),
]

WYGBlog/home/models.py
from django.db import models

from django.contrib.auth.models import User
from django.conf import settings


class Blog(models.Model):
    name = models.CharField('博客名', max_length=20, unique=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='blog', on_delete=models.CASCADE)

    class Meta:
        verbose_name = verbose_name_plural = '博客'

    def __str__(self):
        return self.name

WYGBlog/home/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.db.models import Q
from django.shortcuts import get_object_or_404

from .models import Blog
from homeconfig.models import Category as SiteCategory, SideBar, TopBar, BlogSettings
from blog.models import Post


class CommonViewMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({'sidebars': SideBar.get_all()})  # 侧边栏
        context.update(SiteCategory.get_all())  # 分类导航
        context.update({'top_bars': TopBar.get_all()})  # 顶部菜单

        blog_setting = BlogSettings.get_dict()  # 站点配置
        context.update(dict(blog_setting))
        return context


class HomeListView(CommonViewMixin, ListView):
    paginate_by = 5
    template_name = 'home/index.html'
    context_object_name = 'posts'

    def __init__(self):
        super().__init__()
        blog_settings = BlogSettings.objects.first()
        if blog_settings:
            HomeListView.paginate_by = blog_settings.get_dict().get('index_post_count')

    def get_queryset(self):
        posts = Post.latest_posts()
        return posts


class SearchView(HomeListView):
    def get_queryset(self):
        queryset = super().get_queryset()
        keyword = self.request.GET.get('keyword', '')
        if not keyword:
            return queryset
        return queryset.filter(Q(title__icontains=keyword) | Q(desc__icontains=keyword))


class CategoryView(HomeListView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_id = self.kwargs.get('category_id')
        category = get_object_or_404(SiteCategory, pk=category_id)
        context.update({'category': category})
        return context

    def get_queryset(self):
        """重写queryset，根据分类过滤"""
        queryset = super().get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(site_category_id=category_id)

WYGBlog/WYGBlog/themes/bootstrap/templates/home/base.html
{% load static %}
{% load cache %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}首页{% endblock %} - WYG博客</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
    <style>
        .fixed-header {
            position: sticky;
            position: -webkit-sticky;
            top: 0;
            z-index: 999;
        }
    </style>
    {% block extra_head %}

    {% endblock %}
</head>
<body>
<div class="container head fixed-header">
    <nav class="navbar navbar-expand-lg navbar-default bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div style="float: left">
                <ul class="nav navbar-nav">
                    <li class="nav-item"><a href="{% url 'home:index' %}" class="nav-link">首页</a></li>
                </ul>
            </div>

            <div style="float: right;">
                <div style="float: left;">
                    <ul class="nav navbar-nav">
                        {% for top_bar in top_bars %}
                            <li class="nav-item">
                                {% if top_bar.display_type == 1 %}
                                    <a class="nav-link" href="{{ top_bar.link }}" target="_blank">{{ top_bar.name }}</a>
                                {% elif top_bar.display_type == 2 %}
                                    {% if user.is_authenticated %}
                                        {#我的博客顶栏，只有当用户登录了才显示，href根据当前用户动态填充#}
                                        <a class="nav-link"
                                           href="{% url 'blog:index' user.blog.name %}">{{ top_bar.name }}</a>
                                    {% endif %}
                                {% elif top_bar.display_type == 3 %}
{#                                    只有超级用户，才会显示管理功能#}
                                    {% if user.is_superuser %}
                                        <a class="nav-link" href="{{ top_bar.link }}">{{ top_bar.name }}</a>
                                    {% endif %}
                                {% endif %}
                            </li>
                        {% endfor %}
                        {#                        <li class="nav-item"><a href="#" class="nav-link">|</a></li>#}
                        {% for nav_category in nav_categories %}
                            <li class="nav-item">
                                <a class="nav-link"
                                   href="{% url 'home:category' nav_category.id %}">{{ nav_category.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div style="float: left;">
                    <form action="{% url 'home:search' %}" class="navbar-form navbar-right" method="get">
                        <input type="search" class="form-control mr-sm-2"
                               placeholder="Search" aria-label="Search" name="keyword" value="{{ keyword }}">
                        <button class="btn btn-outline-success" type="submit">搜索</button>
                    </form>
                </div>

                <div class="dropdown" style="float: right;margin: 8px 0 0 10px">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        <a href="#">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                            {% if user.is_authenticated %}
                                <span class="glyphicon-class">{{ user.username }}</span>
                            {% endif %}
                        </a>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'user:index' %}">我的主页</a></li>
                            <li><a href="{% url 'logout' %}?next={{ request.path }}">注销</a></li>
                            <li role="separator" class="divider"></li>
                        {% else %}
                            <li><a href="{% url 'user:register' %}?next={{ request.path }}">注册</a></li>
                            <li><a href="{% url 'login' %}?next={{ request.path }}">登录</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </nav>
</div>

<div class="container main main2">
    <div class="row">
        <div class="col-lg-3">
            {% block sidebar %}
                {% for sidebar in sidebars %}
                    <div class="panel panel-default">
                        <div class="panel-heading">{{ sidebar.title }}</div>
                        <ul class="list-group">
                            {% if sidebar.display_type == 1 %}  {# 显示html不需要转义 #}
                                {{ sidebar.content_html|safe }}
                            {% else %}
                                {{ sidebar.content_html }}
                            {% endif %}
                        </ul>
                    </div>
                {% endfor %}
            {% endblock %}
        </div>

        <div class="col-lg-9 post-list">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</div>

<footer class="footer">
    {% block footer %}
        <div class="container">
            <hr>
            <nav class="nav category">
                {% for normal_category in normal_categories %}
                    <a href="{% url 'home:category' normal_category.id %}"
                       class="nav-link">{{ normal_category.name }}</a>
                {% endfor %}
            </nav>
        </div>
        <div class="container power" style="text-align: center;">
            <span class="text-muted">Power by WYGBlog@wangyangang</span>
            <span class="text-muted">京ICP备19041399号</span>
        </div>
    {% endblock %}
</footer>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/dropdown.js' %}"></script>
</body>
</html>

WYGBlog/WYGBlog/themes/bootstrap/templates/home/index.html
{% extends "home/base.html" %}

{% block title %}
    {% if category %}
        分类页：{{ category.name }}
    {% elif tag %}
        标签页：{{ tag.name }}
    {% else %}
        首页
    {% endif %}
{% endblock %}

{% block content %}
    {% for post in posts %}
        <h5 class="card-title">
            <a href="{% url 'blog:post' post.blog.name post.id %}">{{ post.title }}</a>
        </h5>
        <div class="tag-font">
            <span class="card-link">作者: <a
                    href="{% url 'blog:author' post.blog.name post.blog.user_id %}">{{ post.blog.user.username }}</a></span>&nbsp;
            <span class="card-link">分类:<a
                    href="{% url 'blog:category' post.blog.name post.category.id %}">{{ post.category.name }}</a></span>
            <span class="card-link">标签:
                {% for tag in post.tag.all %}
                    <a href="{% url 'blog:tag' tag.blog.name tag.id %}">{{ tag.name }}</a>
                {% endfor %}
                        </span>
        </div>
        <p class="card-text">{{ post.desc }}<a href="{% url 'blog:post' post.blog.name post.id %}">完整内容</a></p>
        <hr>
    {% endfor %}

    <!--分页-->
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
    {% endif %}
    Page {{ page_obj.number }} of {{ paginator.num_pages }}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">下一页</a>
    {% endif %}
{% endblock %}